server:
  port: 8080
  read_timeout: 3
  write_timeout: 3

db:
  host: localhost
  port: 5432
  user: user
  password: password
  db_name: category_svc
  ssl_mode: disable
  min_conn: 3
  max_conn: 200

redis:
  addr: localhost:6379
  min_conn: 5

kafka:
  broker: localhost:9092