kafka:
  broker: localhost:9092

db:
  host: localhost
  port: 5432
  user: user
  password: password
  db_name: category_svc
  ssl_mode: disable
  min_conn: 2
  max_conn: 10

redis:
  addr: localhost:6379
  min_conn: 2