services:
  db:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379

volumes:
  db_data:
    driver: local