### Healthcheck
GET http://localhost:8080/health

### List unreserved tickets
GET http://localhost:8080/api/tickets

### Create order
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "category_id": 1,
  "email": "arya2@test.com"
}

### Payment notification
POST http://localhost:8080/api/payments/notify
Content-Type: application/json

{
  "status_code": "200",
  "order_id": "25635586309",
  "transaction_status": "settlement"
}