kafka:
  broker: localhost:9092

db:
  host: localhost
  port: 5434
  user: user
  password: password
  db_name: scheduler
  ssl_mode: disable
  min_conn: 2
  max_conn: 200

redis:
  addr: localhost:6379
  min_conn: 5